# Generated by Django 3.2.9 on 2023-03-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='vcompany_name',
        ),
    ]
