# Generated by Django 3.2.9 on 2023-04-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='vcompany_name',
        ),
    ]
