# Generated by Django 3.2.9 on 2023-04-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_itemmodel_vcompany_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardmodel',
            name='item',
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='item_code',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
