# Generated by Django 3.2.9 on 2023-03-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_vehiclemodel_vcompany_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='discount',
        ),
    ]
