# Generated by Django 3.2.9 on 2023-04-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230403_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
