# Generated by Django 3.2.9 on 2023-04-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_dashboardmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
