# Generated by Django 3.2.9 on 2023-04-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_dashboardmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('loaction', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='sold_at',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='sold_to',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
