# Generated by Django 3.2.9 on 2023-04-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_dashboardmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodel',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
