# Generated by Django 3.2.9 on 2023-04-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230401_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationmodel',
            old_name='loaction',
            new_name='location',
        ),
    ]
