# Generated by Django 4.1.5 on 2023-04-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_dashboardmodel_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Medicine Name')),
                ('manufacturer', models.CharField(max_length=1024, verbose_name='Manufacturer')),
                ('category', models.CharField(max_length=1024, verbose_name='Category')),
                ('description', models.TextField(max_length=1024, verbose_name='Description or Ingredient')),
                ('price', models.PositiveBigIntegerField(verbose_name='Medicine Price')),
                ('quantity', models.PositiveBigIntegerField(verbose_name='Quantity')),
                ('location_rack', models.CharField(max_length=1024, verbose_name='Rack Location Medicine')),
            ],
        ),
    ]
